version: 2.1
jobs:
  build:
    docker: 
      - image: registry.lil.tools/cimg/python:3.7.5
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            pip install .
            python -m pytest
