version: 2.1
jobs:
  build:
    docker: 
      - image: registry.lil.tools/cimg/python:3.7.12
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            pip install poetry
            poetry run pip install --upgrade pip
            poetry install
            poetry run flake8
            poetry run pytest
